# Rewrite this meta pipeline configuration as Semaphore YML.
#
# Everything except for Bash commands and those that begin with "git",
# "bundle" and "npm" needs to be translated into Semaphore-specific
# configuration.

# use the image you created in se-base-image 
run_all_jobs_in_docker_image: your-username/your-base-image:version

setup_before_all_jobs:
  commands:
    - checkout source code
    - restore ruby bundle cache
    - restore nodejs cache

pipeline_blocks:
  - name: build dependencies
      jobs:
        before:
          - checkout dependencies from cache
        - name: ruby deps
          commands:
            - bundle install --path vendor/bundle
            - store bundle in cache
        - name: node deps
          commands:
            - npm install
            - store npm packages in cache

  - name: ruby tests
    runs_after: build dependencies
    jobs:
      - name: unit tests
        commands:
          - echo "running ruby unit tests"
          - sleep 2
      - name: integration tests
        commands:
          - echo "running ruby integration tests"
          - sleep 5

  - name: nodejs tests
    runs_after: build dependencies
    commands:
      - echo "running nodejs tests"
      - sleep 3

  - name: build website
    runs_after: nodejs tests
    commands:
      - restore nodejs cache
      - mkdir website
      - echo "<h1>Hello</h1>" >> website/index.html
      - store website/ directory as artifact

if_everything_passed:
  pipeline_blocks:
    - name: upload website
      manual: true
      commands:
        - get website content from artifact store
        - grep "Hello" website/*
        - echo "uploading website..."
        - sleep 4

    - name: sanity check website
      commands:
        - echo "sanity checking website"
        - sleep 2
